availableSecrets:
  secretManager:
    - versionName: projects/782806232816/secrets/APPLICATION/versions/latest
      env: SECRET_ENV_LOCAL
    - versionName: projects/782806232816/secrets/APPLICATION-REMOTE/versions/latest
      env: SECRET_ENV_REMOTE
    - versionName: projects/782806232816/secrets/GCS-KEY/versions/latest
      env: SECRET_ENV_KEY

steps:
  # 🔹 1. LOCAL 서비스용 secret 파일 생성 + 빌드 + 배포
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$SECRET_ENV_LOCAL" > src/main/resources/secret.yml
        echo "$$SECRET_ENV_KEY" > src/main/resources/custhumb.json
    secretEnv: ['SECRET_ENV_LOCAL','SECRET_ENV_KEY']

  - name: gradle:8.5-jdk21
    args: [ 'gradle','build' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'asia-northeast3-docker.pkg.dev/custhumb/custhumb-registry/custhumb-local',
           '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'asia-northeast3-docker.pkg.dev/custhumb/custhumb-registry/custhumb-local']

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        'compute', 'instances', 'update-container',
        'custhumb-local-instance',
        '--zone', 'asia-northeast3-c',
        '--container-image', 'asia-northeast3-docker.pkg.dev/custhumb/custhumb-registry/custhumb-local'
      ]

  # 🔹 2. REMOTE 서비스용 secret 파일 생성 + 빌드 + 배포
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$SECRET_ENV_REMOTE" > src/main/resources/secret.yml
        echo "$$SECRET_ENV_KEY" > src/main/resources/custhumb.json
    secretEnv: [ 'SECRET_ENV_REMOTE','SECRET_ENV_KEY' ]

  - name: gradle:8.5-jdk21
    args: [ 'gradle','build' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'asia-northeast3-docker.pkg.dev/custhumb/custhumb-registry/custhumb-remote',
           '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'asia-northeast3-docker.pkg.dev/custhumb/custhumb-registry/custhumb-remote']

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "custhumb-server-remote",
        "--image",  "asia-northeast3-docker.pkg.dev/custhumb/custhumb-registry/custhumb-remote",
        "--region", "asia-northeast3",
        "--platform", "managed",
        "--allow-unauthenticated",
      ]

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

images:
  - 'asia-northeast3-docker.pkg.dev/custhumb/custhumb-registry/custhumb-local'
  - 'asia-northeast3-docker.pkg.dev/custhumb/custhumb-registry/custhumb-remote'
