availableSecrets:
  secretManager:
    - versionName: projects/582289918705/secrets/APPLICATION/versions/latest
      env: SECRET_ENV_LOCAL
    - versionName: projects/582289918705/secrets/APPLICATION-REMOTE/versions/latest
      env: SECRET_ENV_REMOTE

steps:
  # ðŸ”¹ 1. LOCAL ì„œë¹„ìŠ¤ìš© secret íŒŒì¼ ìƒì„± + ë¹Œë“œ + ë°°í¬
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$SECRET_ENV_LOCAL" > src/main/resources/secret.yml
    secretEnv: ['SECRET_ENV_LOCAL']

  - name: gradle:7.6-jdk17
    args: [ 'gradle','build' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'asia-northeast3-docker.pkg.dev/custhumb/custhumb-registry/custhumb-local',
           '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'asia-northeast3-docker.pkg.dev/custhumb/custhumb-registry/custhumb-local']

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "planpal-server-local",
        "--image", "asia-northeast3-docker.pkg.dev/custhumb/custhumb-registry/custhumb-local",
        "--region", "asia-northeast3",
        "--platform", "managed",
        "--allow-unauthenticated",
      ]

  # ðŸ”¹ 2. REMOTE ì„œë¹„ìŠ¤ìš© secret íŒŒì¼ ìƒì„± + ë¹Œë“œ + ë°°í¬
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$SECRET_ENV_REMOTE" > src/main/resources/secret.yml
    secretEnv: ['SECRET_ENV_REMOTE']

  - name: gradle:7.6-jdk17
    args: [ 'gradle','build' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'asia-northeast3-docker.pkg.dev/custhumb/custhumb-registry/custhumb-remote',
           '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'asia-northeast3-docker.pkg.dev/custhumb/custhumb-registry/custhumb-remote']

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "planpal-server-remote",
        "--image",  "asia-northeast3-docker.pkg.dev/custhumb/custhumb-registry/custhumb-remote",
        "--region", "asia-northeast3",
        "--platform", "managed",
        "--allow-unauthenticated",
      ]

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'asia-northeast3-docker.pkg.dev/custhumb/custhumb-registry/custhumb-local'
  - 'asia-northeast3-docker.pkg.dev/custhumb/custhumb-registry/custhumb-remote'
